name: Run tests

on:
  # Make workflow callable.
  workflow_call:
  push:
    branches:
      # Run tests on all branches except "main".
      - "**"
      - "!main"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python Poetry
        uses: snok/install-poetry@v1

      - name: Ensure README.rst builds correctly for PyPI
        run: |
          poetry add readme-renderer
          python -m readme_renderer README.rst

      - name: Run pytest
        run: echo todo
